=== APIOpsCycles/apiops-cycles-method-data/src/schemas/import-export-template.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["templateId", "locale", "metadata", "sections"],
  "additionalProperties": false,
  "properties": {
    "templateId": {"type": "string"},
    "locale": {"type": "string"},
    "metadata": {
      "type": "object",
      "required": ["source", "license", "authors", "website"],
      "properties": {
        "source": {"type": "string"},
        "license": {"type": "string"},
        "authors": {"type": "array", "items": {"type": "string"}},
        "website": {"type": "string"},
        "date": {"type": "string"}
      },
      "additionalProperties": false
    },
    "sections": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["sectionId", "stickyNotes"],
        "additionalProperties": false,
        "properties": {
          "sectionId": {"type": "string"},
          "stickyNotes": {
            "type": "array",
            "items": {
              "type": "object",
              "required": ["content", "size", "color"],
              "additionalProperties": false,
              "properties": {
                "content": {"type": "string"},
                "size": {"type": "number"},
                "color": {
                  "type": "string",
                  "pattern": "^#[0-9A-Fa-f]{6}$"
                },
                "position": {"type": "object",
                     "properties": {
                       "x": {"type": "number"},
                       "y": {"type": "number"}
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== APIOpsCycles/apiops-cycles-method-data/src/data/canvas/import-export-templates/Canvas_graphqlCanvas.json
{
  "templateId": "graphqlCanvas",
  "locale": "en-US",
  "metadata": {
    "source": "",
    "license": "",
    "authors": [],
    "website": ""
  },
  "sections": [
    {
      "sectionId": "apiName",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#FFF399"
        }
      ]
    },
    {
      "sectionId": "consumerGoals",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#C0EB6A"
        }
      ]
    },
    {
      "sectionId": "keyTypes",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    },
    {
      "sectionId": "relationships",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    },
    {
      "sectionId": "queries",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#7DC9E7"
        }
      ]
    },
    {
      "sectionId": "mutations",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#7DC9E7"
        }
      ]
    },
    {
      "sectionId": "subscriptions",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#7DC9E7"
        }
      ]
    },
    {
      "sectionId": "authorizationRules",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#FFAFAF"
        }
      ]
    },
    {
      "sectionId": "consumerConstraints",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#FFAFAF"
        }
      ]
    },
    {
      "sectionId": "openQuestions",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#FFF399"
        }
      ]
    }
  ]
}

=== APIOpsCycles/apiops-cycles-method-data/src/data/canvas/import-export-templates/Canvas_capacityCanvas.json
{
  "templateId": "capacityCanvas",
  "locale": "en-US",
  "metadata": {
    "source": "",
    "license": "",
    "authors": [],
    "website": ""
  },
  "sections": [
    {
      "sectionId": "currentBusinessVolumes",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    },
    {
      "sectionId": "futureConsumptionTrends",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    },
    {
      "sectionId": "peakLoadAndAvailabilityRequirements",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    },
    {
      "sectionId": "cachingStrategies",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#7DC9E7"
        }
      ]
    },
    {
      "sectionId": "rateLimitingStrategies",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#7DC9E7"
        }
      ]
    },
    {
      "sectionId": "scalingStrategies",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#7DC9E7"
        }
      ]
    }
  ]
}

=== APIOpsCycles/apiops-cycles-method-data/src/data/canvas/import-export-templates/Canvas_locationsCanvas.json
{
  "templateId": "locationsCanvas",
  "locale": "en-US",
  "metadata": {
    "source": "",
    "license": "",
    "authors": [],
    "website": ""
  },
  "sections": [
    {
      "sectionId": "locationGroups",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    },
    {
      "sectionId": "locationGroupCharacteristics",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    },
    {
      "sectionId": "locations",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    },
    {
      "sectionId": "locationCharacteristics",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    },
    {
      "sectionId": "locationDistances",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#FFAFAF"
        }
      ]
    },
    {
      "sectionId": "locationDistanceCharacteristics",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    },
    {
      "sectionId": "locationEndpoints",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    },
    {
      "sectionId": "locationEndpointCharacteristics",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    }
  ]
}

=== APIOpsCycles/apiops-cycles-method-data/src/data/canvas/import-export-templates/Canvas_interactionCanvas.json
{
  "templateId": "interactionCanvas",
  "locale": "en-US",
  "metadata": {
    "source": "",
    "license": "",
    "authors": [],
    "website": ""
  },
  "sections": [
    {
      "sectionId": "crudInteractions",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#7DC9E7"
        }
      ]
    },
    {
      "sectionId": "crudInputOutputModels",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    },
    {
      "sectionId": "crudProcessingValidation",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    },
    {
      "sectionId": "queryDrivenInteractions",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#7DC9E7"
        }
      ]
    },
    {
      "sectionId": "queryDrivenInputOutputModels",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    },
    {
      "sectionId": "queryDrivenProcessingValidation",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    },
    {
      "sectionId": "commandDrivenInteractions",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#7DC9E7"
        }
      ]
    },
    {
      "sectionId": "commandDrivenInputOutputModels",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    },
    {
      "sectionId": "commandDrivenProcessingValidation",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    },
    {
      "sectionId": "eventDrivenInteractions",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#7DC9E7"
        }
      ]
    },
    {
      "sectionId": "eventDrivenInputOutputModels",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    },
    {
      "sectionId": "eventDrivenProcessingValidation",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    }
  ]
}

=== APIOpsCycles/apiops-cycles-method-data/src/data/canvas/import-export-templates/Canvas_apiValuePropositionCanvas.json
{
  "templateId": "apiValuePropositionCanvas",
  "locale": "en-US",
  "metadata": {
    "source": "",
    "license": "",
    "authors": [],
    "website": ""
  },
  "sections": [
    {
      "sectionId": "tasks",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#7DC9E7"
        }
      ]
    },
    {
      "sectionId": "gainEnablingFeatures",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#C0EB6A"
        }
      ]
    },
    {
      "sectionId": "painRelievingFeatures",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#C0EB6A"
        }
      ]
    },
    {
      "sectionId": "apiProducts",
      "stickyNotes": [
        {
          "content": "Placeholder",
          "size": 80,
          "color": "#DFDDC5"
        }
      ]
    }
  ]
}
